apiVersion: kp.kpack.io/v1alpha3
kind: DependencyDescriptor
defaultClusterBuilder: base
defaultClusterStack: base
lifecycle:
  image: registry.pivotal.io/tbs-dependencies/lifecycle@sha256:c923a81a1c3908122e29a30bae5886646d6ec26429bad4842c67103636041d93
clusterStores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:27b33492bfb9d8116b2689237161aecdaf7033a0f4b1e917481a70b58575ab2d
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:e7fd464a33a3c72c06874810719a03f88a3d45434c982ee9c0ae8f6434a53697
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:bc68b0d3c42eff1b9729c6a20fd22a1669a463c8adc4bbae2757972bcd5a6476
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:1470f053e4cc0d912d356f2299ae3fa195ab1baaabf1ce095cde184dab6759cc
  - image: registry.pivotal.io/tanzu-dotnet-core-buildpack/dotnet-core@sha256:6d57e312e7ac86f78ece4afcc3967e5314fbb71fe592800fd6f0f58bd923945a
  - image: registry.pivotal.io/tanzu-python-buildpack/python@sha256:6364d1cc1695f9a20a65604d61f6ca8ceb05567d1512f67d13b7c150f326bf08
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:27f003c0ad6d45fd78cd9dbb71ae55b5ba1e599d8facfd98269dd29f42028870
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:5798dfecab8a4c67bbc3b956b6bef4474c52197b8949f02b8b866e19bfcde71e
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:4e15987d21d3d4f0cbc6be0d3b283db1d3f368eb15d0b1b59d835899c8bf946c
  - image: registry.pivotal.io/tbs-dependencies/paketo-buildpacks_procfile@sha256:cc3910850249adb0b7b2f6850a362dbfbfad1df976b8736ac2c90ff70093fb4e
clusterStacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/build@sha256:36145b346953b8a938c2ace2728697f43987370f6670f013c7efe2f3fde43b2b
  runImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/run@sha256:b643257f93f44aa4e77c1c746fea14f419e29a2123829c7a228bc7f1b633fe2a
- name: base
  buildImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/build@sha256:406b1f02b5dee647a131d623013c869f4ab1bc676d339085652fc962b9fb4b71
  runImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/run@sha256:8d05ba1977ffef1e1499667d8e468fc60ebf1cc77d4df4c97aa10dd350c3b76f
- name: full
  buildImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/build@sha256:b133e250f0c85f031f07eb9f65bd55a27b25180591eace5c2b26e84e1f3da07e
  runImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/run@sha256:da5a2cef27b6ced0f535a7b0083ed2d321eb3d5b3549ab492872506dfd5a8bb8
clusterBuilders:
- name: base
  clusterStack: base
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  clusterStack: full
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  clusterStack: tiny
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
